# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Project',            url: 'project'}
- {name: 'About Me',           url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  # Replace the placeholders below with your actual profiles
  - {icon: 'github',   link: 'https://github.com/vvhuiling'}
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/huiling-huang-7aa8a3249/'}
  - {icon: 'envelope', link: 'mailto:hhuang040@e.ntu.edu.sg'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
